### ISSUE TITLE
Prebuilt Image

### ISSUE THREAD

**Issue by dnorthcote** [sarafs1926/ZCU216-PYNQ#1]
Hi @sarafs1926,

Firstly, I just want to say that this is an excellent repository and really useful for our team.

Do you have a prebuilt ZCU216 image available for download? Normally I would expect to see this on the releases page [here](https://github.com/sarafs1926/ZCU216-PYNQ/releases).

I greatly appreciate your help,

Thanks,
David.

**Comment by sarafs1926** [comment]
Hi @dnorthcote, 

Great to hear from you! Yeah, I currently have uploaded one on Google Drive here for people's convenience: https://drive.google.com/file/d/10kDKrEqA4l0_S3ysTlWbbOHgTsV0Zpyq/view?usp=sharing

Let me know if that helps!

Best,

Sara

**Comment by dnorthcote** [comment]
Hi @sarafs1926, 

Thank you very much for the fast response and I greatly appreciate a link to the download.

I'll let you know how we get on!

Thanks,
David.
